services:
  nginx:
    image: nginx:1.13
    container_name: provectus-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql/mysql-server:5.7
    container_name: provectus-mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 143625
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mysql_data:
