version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_web
    restart: always
    networks:
      lan_net:
        ipv4_address: 10.0.2.50  # <-- choose an unused IP in your subnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      EXTERNAL_LAN:
        ipv4_address: 10.10.10.117
      internal_net:
        aliases:
          - nginx

  mysql:
    image: mysql/mysql-server:5.7
    container_name: provectus-mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 143625
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal_net
    restart: unless-stopped

  app:
    build: ./app
    container_name: provectus-app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
    networks:
      - internal_net
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  lan_net:
    external: true

  # External LAN bridge (custom subnet to avoid overlap)
  EXTERNAL_LAN:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
