version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - mysql
    networks:
      lan_net:
        ipv4_address: 172.28.94.50

  mysql:
    image: mysql/mysql-server:5.7
    container_name: provectus-mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 143625
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      lan_net:
        aliases:
          - mysql
    restart: unless-stopped

  app:
    build: ./app
    container_name: provectus-app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
    networks:
      lan_net:
        aliases:
          - app
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  lan_net:
    driver: macvlan
    driver_opts:
      parent: eth0  # change to your actual host interface if needed
    ipam:
      config:
        - subnet: 172.28.94.0/24
          gateway: 172.28.94.1
