version: "3.8"

services:
  nginx:
    image: nginx:1.13
    container_name: provectus-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      lan_net:
        ipv4_address: 10.0.2.117  # 👈 static LAN IP
      internal_net:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql/mysql-server:5.7
    container_name: provectus-mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 143625
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
    networks:
      - internal_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mysql_data:

networks:
  lan_net:
    external: true  # 👈 we already created it manually
  internal_net:
    driver: bridge
